// <auto-generated />
namespace SukkuShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OrdersEnhancement2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdersEnhancement2));
        
        string IMigrationMetadata.Id
        {
            get { return "201412302123352_OrdersEnhancement2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
