// <auto-generated />
namespace SukkuShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class shipping_payment_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shipping_payment_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201501121827340_shipping_payment_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
