// <auto-generated />
namespace SukkuShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ProductWeight_cd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductWeight_cd));
        
        string IMigrationMetadata.Id
        {
            get { return "201502201422583_ProductWeight_cd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
