// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Areas.Admin.Controllers
{
    public partial class ContentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ContentController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ContentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ContentController Actions { get { return MVC.Admin.Content; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Content";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Content";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Regulamin = "Regulamin";
            public readonly string RegulaminAjaxGet = "RegulaminAjaxGet";
            public readonly string RegulaminAjaxPost = "RegulaminAjaxPost";
            public readonly string PolitykaPrywatnosci = "PolitykaPrywatnosci";
            public readonly string PolitykaPrywatnosciAjaxGet = "PolitykaPrywatnosciAjaxGet";
            public readonly string PolitykaPrywatnosciAjaxPost = "PolitykaPrywatnosciAjaxPost";
            public readonly string Gwarancja = "Gwarancja";
            public readonly string GwarancjaAjaxGet = "GwarancjaAjaxGet";
            public readonly string GwarancjaAjaxPost = "GwarancjaAjaxPost";
            public readonly string Reklamacje = "Reklamacje";
            public readonly string ReklamacjeAjaxGet = "ReklamacjeAjaxGet";
            public readonly string ReklamacjeAjaxPost = "ReklamacjeAjaxPost";
            public readonly string ZwrotTowarow = "ZwrotTowarow";
            public readonly string ZwrotTowarowAjaxGet = "ZwrotTowarowAjaxGet";
            public readonly string ZwrotTowarowAjaxPost = "ZwrotTowarowAjaxPost";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Regulamin = "Regulamin";
            public const string RegulaminAjaxGet = "RegulaminAjaxGet";
            public const string RegulaminAjaxPost = "RegulaminAjaxPost";
            public const string PolitykaPrywatnosci = "PolitykaPrywatnosci";
            public const string PolitykaPrywatnosciAjaxGet = "PolitykaPrywatnosciAjaxGet";
            public const string PolitykaPrywatnosciAjaxPost = "PolitykaPrywatnosciAjaxPost";
            public const string Gwarancja = "Gwarancja";
            public const string GwarancjaAjaxGet = "GwarancjaAjaxGet";
            public const string GwarancjaAjaxPost = "GwarancjaAjaxPost";
            public const string Reklamacje = "Reklamacje";
            public const string ReklamacjeAjaxGet = "ReklamacjeAjaxGet";
            public const string ReklamacjeAjaxPost = "ReklamacjeAjaxPost";
            public const string ZwrotTowarow = "ZwrotTowarow";
            public const string ZwrotTowarowAjaxGet = "ZwrotTowarowAjaxGet";
            public const string ZwrotTowarowAjaxPost = "ZwrotTowarowAjaxPost";
        }


        static readonly ActionParamsClass_Regulamin s_params_Regulamin = new ActionParamsClass_Regulamin();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Regulamin RegulaminParams { get { return s_params_Regulamin; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Regulamin
        {
            public readonly string text = "text";
        }
        static readonly ActionParamsClass_PolitykaPrywatnosci s_params_PolitykaPrywatnosci = new ActionParamsClass_PolitykaPrywatnosci();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PolitykaPrywatnosci PolitykaPrywatnosciParams { get { return s_params_PolitykaPrywatnosci; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PolitykaPrywatnosci
        {
            public readonly string text = "text";
        }
        static readonly ActionParamsClass_Gwarancja s_params_Gwarancja = new ActionParamsClass_Gwarancja();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Gwarancja GwarancjaParams { get { return s_params_Gwarancja; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Gwarancja
        {
            public readonly string text = "text";
        }
        static readonly ActionParamsClass_Reklamacje s_params_Reklamacje = new ActionParamsClass_Reklamacje();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Reklamacje ReklamacjeParams { get { return s_params_Reklamacje; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Reklamacje
        {
            public readonly string text = "text";
        }
        static readonly ActionParamsClass_ZwrotTowarow s_params_ZwrotTowarow = new ActionParamsClass_ZwrotTowarow();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ZwrotTowarow ZwrotTowarowParams { get { return s_params_ZwrotTowarow; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ZwrotTowarow
        {
            public readonly string text = "text";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _GwarancjaGet = "_GwarancjaGet";
                public readonly string _GwarancjaPost = "_GwarancjaPost";
                public readonly string _PolitykaGet = "_PolitykaGet";
                public readonly string _PolitykaPost = "_PolitykaPost";
                public readonly string _RegulaminGet = "_RegulaminGet";
                public readonly string _RegulaminPost = "_RegulaminPost";
                public readonly string _ReklamacjeGet = "_ReklamacjeGet";
                public readonly string _ReklamacjePost = "_ReklamacjePost";
                public readonly string _ZwrotTowarowGet = "_ZwrotTowarowGet";
                public readonly string _ZwrotTowarowPost = "_ZwrotTowarowPost";
                public readonly string Gwarancja = "Gwarancja";
                public readonly string Index = "Index";
                public readonly string PolitykaPrywatnosci = "PolitykaPrywatnosci";
                public readonly string Regulamin = "Regulamin";
                public readonly string Reklamacje = "Reklamacje";
                public readonly string ZwrotTowarow = "ZwrotTowarow";
            }
            public readonly string _GwarancjaGet = "~/Areas/Admin/Views/Content/_GwarancjaGet.cshtml";
            public readonly string _GwarancjaPost = "~/Areas/Admin/Views/Content/_GwarancjaPost.cshtml";
            public readonly string _PolitykaGet = "~/Areas/Admin/Views/Content/_PolitykaGet.cshtml";
            public readonly string _PolitykaPost = "~/Areas/Admin/Views/Content/_PolitykaPost.cshtml";
            public readonly string _RegulaminGet = "~/Areas/Admin/Views/Content/_RegulaminGet.cshtml";
            public readonly string _RegulaminPost = "~/Areas/Admin/Views/Content/_RegulaminPost.cshtml";
            public readonly string _ReklamacjeGet = "~/Areas/Admin/Views/Content/_ReklamacjeGet.cshtml";
            public readonly string _ReklamacjePost = "~/Areas/Admin/Views/Content/_ReklamacjePost.cshtml";
            public readonly string _ZwrotTowarowGet = "~/Areas/Admin/Views/Content/_ZwrotTowarowGet.cshtml";
            public readonly string _ZwrotTowarowPost = "~/Areas/Admin/Views/Content/_ZwrotTowarowPost.cshtml";
            public readonly string Gwarancja = "~/Areas/Admin/Views/Content/Gwarancja.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Content/Index.cshtml";
            public readonly string PolitykaPrywatnosci = "~/Areas/Admin/Views/Content/PolitykaPrywatnosci.cshtml";
            public readonly string Regulamin = "~/Areas/Admin/Views/Content/Regulamin.cshtml";
            public readonly string Reklamacje = "~/Areas/Admin/Views/Content/Reklamacje.cshtml";
            public readonly string ZwrotTowarow = "~/Areas/Admin/Views/Content/ZwrotTowarow.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ContentController : SukkuShop.Areas.Admin.Controllers.ContentController
    {
        public T4MVC_ContentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegulaminOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Regulamin()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Regulamin);
            RegulaminOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegulaminAjaxGetOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult RegulaminAjaxGet()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.RegulaminAjaxGet);
            RegulaminAjaxGetOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegulaminAjaxPostOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult RegulaminAjaxPost()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.RegulaminAjaxPost);
            RegulaminAjaxPostOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegulaminOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string text);

        [NonAction]
        public override System.Web.Mvc.ActionResult Regulamin(string text)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Regulamin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "text", text);
            RegulaminOverride(callInfo, text);
            return callInfo;
        }

        [NonAction]
        partial void PolitykaPrywatnosciOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PolitykaPrywatnosci()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PolitykaPrywatnosci);
            PolitykaPrywatnosciOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PolitykaPrywatnosciAjaxGetOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult PolitykaPrywatnosciAjaxGet()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.PolitykaPrywatnosciAjaxGet);
            PolitykaPrywatnosciAjaxGetOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PolitykaPrywatnosciAjaxPostOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult PolitykaPrywatnosciAjaxPost()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.PolitykaPrywatnosciAjaxPost);
            PolitykaPrywatnosciAjaxPostOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PolitykaPrywatnosciOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string text);

        [NonAction]
        public override System.Web.Mvc.ActionResult PolitykaPrywatnosci(string text)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PolitykaPrywatnosci);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "text", text);
            PolitykaPrywatnosciOverride(callInfo, text);
            return callInfo;
        }

        [NonAction]
        partial void GwarancjaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Gwarancja()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gwarancja);
            GwarancjaOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GwarancjaAjaxGetOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GwarancjaAjaxGet()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GwarancjaAjaxGet);
            GwarancjaAjaxGetOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GwarancjaAjaxPostOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GwarancjaAjaxPost()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GwarancjaAjaxPost);
            GwarancjaAjaxPostOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GwarancjaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string text);

        [NonAction]
        public override System.Web.Mvc.ActionResult Gwarancja(string text)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gwarancja);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "text", text);
            GwarancjaOverride(callInfo, text);
            return callInfo;
        }

        [NonAction]
        partial void ReklamacjeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Reklamacje()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reklamacje);
            ReklamacjeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReklamacjeAjaxGetOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ReklamacjeAjaxGet()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ReklamacjeAjaxGet);
            ReklamacjeAjaxGetOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReklamacjeAjaxPostOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ReklamacjeAjaxPost()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ReklamacjeAjaxPost);
            ReklamacjeAjaxPostOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReklamacjeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string text);

        [NonAction]
        public override System.Web.Mvc.ActionResult Reklamacje(string text)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reklamacje);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "text", text);
            ReklamacjeOverride(callInfo, text);
            return callInfo;
        }

        [NonAction]
        partial void ZwrotTowarowOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ZwrotTowarow()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ZwrotTowarow);
            ZwrotTowarowOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ZwrotTowarowAjaxGetOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ZwrotTowarowAjaxGet()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ZwrotTowarowAjaxGet);
            ZwrotTowarowAjaxGetOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ZwrotTowarowAjaxPostOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ZwrotTowarowAjaxPost()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ZwrotTowarowAjaxPost);
            ZwrotTowarowAjaxPostOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ZwrotTowarowOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string text);

        [NonAction]
        public override System.Web.Mvc.ActionResult ZwrotTowarow(string text)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ZwrotTowarow);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "text", text);
            ZwrotTowarowOverride(callInfo, text);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
