// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Areas.Admin.Controllers
{
    public partial class ProduktyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProduktyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Lista()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lista);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PublishProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PublishProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UnpublishProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnpublishProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetSubCategoryList()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSubCategoryList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edytuj()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edytuj);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProduktyController Actions { get { return MVC.Admin.Produkty; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Produkty";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Produkty";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Lista = "Lista";
            public readonly string GetProductList = "GetProductList";
            public readonly string PublishProduct = "PublishProduct";
            public readonly string UnpublishProduct = "UnpublishProduct";
            public readonly string DeleteProduct = "DeleteProduct";
            public readonly string Dodaj = "Dodaj";
            public readonly string GetCategoriesCreateEditProduct = "GetCategoriesCreateEditProduct";
            public readonly string GetSubCategoryList = "GetSubCategoryList";
            public readonly string Edytuj = "Edytuj";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Lista = "Lista";
            public const string GetProductList = "GetProductList";
            public const string PublishProduct = "PublishProduct";
            public const string UnpublishProduct = "UnpublishProduct";
            public const string DeleteProduct = "DeleteProduct";
            public const string Dodaj = "Dodaj";
            public const string GetCategoriesCreateEditProduct = "GetCategoriesCreateEditProduct";
            public const string GetSubCategoryList = "GetSubCategoryList";
            public const string Edytuj = "Edytuj";
        }


        static readonly ActionParamsClass_Lista s_params_Lista = new ActionParamsClass_Lista();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Lista ListaParams { get { return s_params_Lista; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Lista
        {
            public readonly string name = "name";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PublishProduct s_params_PublishProduct = new ActionParamsClass_PublishProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PublishProduct PublishProductParams { get { return s_params_PublishProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PublishProduct
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UnpublishProduct s_params_UnpublishProduct = new ActionParamsClass_UnpublishProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UnpublishProduct UnpublishProductParams { get { return s_params_UnpublishProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UnpublishProduct
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteProduct s_params_DeleteProduct = new ActionParamsClass_DeleteProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteProduct DeleteProductParams { get { return s_params_DeleteProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteProduct
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Dodaj s_params_Dodaj = new ActionParamsClass_Dodaj();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Dodaj DodajParams { get { return s_params_Dodaj; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Dodaj
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetSubCategoryList s_params_GetSubCategoryList = new ActionParamsClass_GetSubCategoryList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSubCategoryList GetSubCategoryListParams { get { return s_params_GetSubCategoryList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSubCategoryList
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edytuj s_params_Edytuj = new ActionParamsClass_Edytuj();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edytuj EdytujParams { get { return s_params_Edytuj; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edytuj
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Dodaj = "Dodaj";
                public readonly string Edytuj = "Edytuj";
                public readonly string GetCategoriesCreateEditProduct = "GetCategoriesCreateEditProduct";
                public readonly string Lista = "Lista";
            }
            public readonly string Dodaj = "~/Areas/Admin/Views/Produkty/Dodaj.cshtml";
            public readonly string Edytuj = "~/Areas/Admin/Views/Produkty/Edytuj.cshtml";
            public readonly string GetCategoriesCreateEditProduct = "~/Areas/Admin/Views/Produkty/GetCategoriesCreateEditProduct.cshtml";
            public readonly string Lista = "~/Areas/Admin/Views/Produkty/Lista.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProduktyController : SukkuShop.Areas.Admin.Controllers.ProduktyController
    {
        public T4MVC_ProduktyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ListaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string name, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Lista(string name, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lista);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ListaOverride(callInfo, name, id);
            return callInfo;
        }

        [NonAction]
        partial void GetProductListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetProductList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetProductList);
            GetProductListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PublishProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PublishProduct(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PublishProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PublishProductOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UnpublishProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult UnpublishProduct(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnpublishProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UnpublishProductOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteProduct(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteProductOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DodajOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Areas.Admin.Models.ProductUploadModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Dodaj(SukkuShop.Areas.Admin.Models.ProductUploadModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Dodaj);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DodajOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DodajOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Dodaj()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Dodaj);
            DodajOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetCategoriesCreateEditProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetCategoriesCreateEditProduct()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetCategoriesCreateEditProduct);
            GetCategoriesCreateEditProductOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetSubCategoryListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetSubCategoryList(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSubCategoryList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetSubCategoryListOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EdytujOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edytuj(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edytuj);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EdytujOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EdytujOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Areas.Admin.Models.ProductEditModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edytuj(SukkuShop.Areas.Admin.Models.ProductEditModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edytuj);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EdytujOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
