// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Areas.Admin.Controllers
{
    public partial class DostawyPlatnosciController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DostawyPlatnosciController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeletePayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteShipping()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteShipping);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ActivatePayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActivatePayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeactivatePayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeactivatePayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ActivateShipping()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActivateShipping);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeactivateShipping()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeactivateShipping);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AddPayment()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AddShipping()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddShipping);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult EditShippingDescription()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditShippingDescription);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult EditPaymentDescription()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditPaymentDescription);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DostawyPlatnosciController Actions { get { return MVC.Admin.DostawyPlatnosci; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "DostawyPlatnosci";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "DostawyPlatnosci";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetDataJson = "GetDataJson";
            public readonly string DeletePayment = "DeletePayment";
            public readonly string DeleteShipping = "DeleteShipping";
            public readonly string ActivatePayment = "ActivatePayment";
            public readonly string DeactivatePayment = "DeactivatePayment";
            public readonly string ActivateShipping = "ActivateShipping";
            public readonly string DeactivateShipping = "DeactivateShipping";
            public readonly string AddPayment = "AddPayment";
            public readonly string AddShipping = "AddShipping";
            public readonly string EditShippingDescription = "EditShippingDescription";
            public readonly string EditPaymentDescription = "EditPaymentDescription";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetDataJson = "GetDataJson";
            public const string DeletePayment = "DeletePayment";
            public const string DeleteShipping = "DeleteShipping";
            public const string ActivatePayment = "ActivatePayment";
            public const string DeactivatePayment = "DeactivatePayment";
            public const string ActivateShipping = "ActivateShipping";
            public const string DeactivateShipping = "DeactivateShipping";
            public const string AddPayment = "AddPayment";
            public const string AddShipping = "AddShipping";
            public const string EditShippingDescription = "EditShippingDescription";
            public const string EditPaymentDescription = "EditPaymentDescription";
        }


        static readonly ActionParamsClass_DeletePayment s_params_DeletePayment = new ActionParamsClass_DeletePayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePayment DeletePaymentParams { get { return s_params_DeletePayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePayment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteShipping s_params_DeleteShipping = new ActionParamsClass_DeleteShipping();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteShipping DeleteShippingParams { get { return s_params_DeleteShipping; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteShipping
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ActivatePayment s_params_ActivatePayment = new ActionParamsClass_ActivatePayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActivatePayment ActivatePaymentParams { get { return s_params_ActivatePayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActivatePayment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeactivatePayment s_params_DeactivatePayment = new ActionParamsClass_DeactivatePayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeactivatePayment DeactivatePaymentParams { get { return s_params_DeactivatePayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeactivatePayment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ActivateShipping s_params_ActivateShipping = new ActionParamsClass_ActivateShipping();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActivateShipping ActivateShippingParams { get { return s_params_ActivateShipping; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActivateShipping
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeactivateShipping s_params_DeactivateShipping = new ActionParamsClass_DeactivateShipping();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeactivateShipping DeactivateShippingParams { get { return s_params_DeactivateShipping; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeactivateShipping
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddPayment s_params_AddPayment = new ActionParamsClass_AddPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddPayment AddPaymentParams { get { return s_params_AddPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddPayment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddShipping s_params_AddShipping = new ActionParamsClass_AddShipping();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddShipping AddShippingParams { get { return s_params_AddShipping; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddShipping
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditShippingDescription s_params_EditShippingDescription = new ActionParamsClass_EditShippingDescription();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditShippingDescription EditShippingDescriptionParams { get { return s_params_EditShippingDescription; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditShippingDescription
        {
            public readonly string id = "id";
            public readonly string description = "description";
        }
        static readonly ActionParamsClass_EditPaymentDescription s_params_EditPaymentDescription = new ActionParamsClass_EditPaymentDescription();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditPaymentDescription EditPaymentDescriptionParams { get { return s_params_EditPaymentDescription; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditPaymentDescription
        {
            public readonly string id = "id";
            public readonly string description = "description";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Areas/Admin/Views/DostawyPlatnosci/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DostawyPlatnosciController : SukkuShop.Areas.Admin.Controllers.DostawyPlatnosciController
    {
        public T4MVC_DostawyPlatnosciController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetDataJsonOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetDataJson()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetDataJson);
            GetDataJsonOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeletePaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeletePayment(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeletePaymentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteShippingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteShipping(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteShipping);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteShippingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ActivatePaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActivatePayment(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActivatePayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ActivatePaymentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeactivatePaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeactivatePayment(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeactivatePayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeactivatePaymentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ActivateShippingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActivateShipping(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActivateShipping);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ActivateShippingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeactivateShippingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeactivateShipping(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeactivateShipping);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeactivateShippingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddPaymentOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, SukkuShop.Areas.Admin.Models.ShippingPaymentCreateModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddPayment(SukkuShop.Areas.Admin.Models.ShippingPaymentCreateModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddPaymentOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddShippingOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, SukkuShop.Areas.Admin.Models.ShippingPaymentCreateModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddShipping(SukkuShop.Areas.Admin.Models.ShippingPaymentCreateModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddShipping);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddShippingOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditShippingDescriptionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id, string description);

        [NonAction]
        public override System.Web.Mvc.JsonResult EditShippingDescription(int id, string description)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditShippingDescription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "description", description);
            EditShippingDescriptionOverride(callInfo, id, description);
            return callInfo;
        }

        [NonAction]
        partial void EditPaymentDescriptionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id, string description);

        [NonAction]
        public override System.Web.Mvc.JsonResult EditPaymentDescription(int id, string description)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditPaymentDescription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "description", description);
            EditPaymentDescriptionOverride(callInfo, id, description);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
