// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Areas.Admin.Controllers
{
    public partial class ZamowieniaController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ZamowieniaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult ChangeOrderStateFromDetails()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ChangeOrderStateFromDetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ZamowieniaController Actions { get { return MVC.Admin.Zamowienia; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Zamowienia";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Zamowienia";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetOrdersList = "GetOrdersList";
            public readonly string ChangeOrderStateFromDetails = "ChangeOrderStateFromDetails";
            public readonly string SzczegolyZamowienia = "SzczegolyZamowienia";
            public readonly string DownloadInvoice = "DownloadInvoice";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetOrdersList = "GetOrdersList";
            public const string ChangeOrderStateFromDetails = "ChangeOrderStateFromDetails";
            public const string SzczegolyZamowienia = "SzczegolyZamowienia";
            public const string DownloadInvoice = "DownloadInvoice";
        }


        static readonly ActionParamsClass_ChangeOrderStateFromDetails s_params_ChangeOrderStateFromDetails = new ActionParamsClass_ChangeOrderStateFromDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeOrderStateFromDetails ChangeOrderStateFromDetailsParams { get { return s_params_ChangeOrderStateFromDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeOrderStateFromDetails
        {
            public readonly string id = "id";
            public readonly string value = "value";
            public readonly string packageNumber = "packageNumber";
        }
        static readonly ActionParamsClass_SzczegolyZamowienia s_params_SzczegolyZamowienia = new ActionParamsClass_SzczegolyZamowienia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SzczegolyZamowienia SzczegolyZamowieniaParams { get { return s_params_SzczegolyZamowienia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SzczegolyZamowienia
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ChangeOrderStateFromDetails = "_ChangeOrderStateFromDetails";
                public readonly string Index = "Index";
                public readonly string SzczegolyZamowienia = "SzczegolyZamowienia";
            }
            public readonly string _ChangeOrderStateFromDetails = "~/Areas/Admin/Views/Zamowienia/_ChangeOrderStateFromDetails.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Zamowienia/Index.cshtml";
            public readonly string SzczegolyZamowienia = "~/Areas/Admin/Views/Zamowienia/SzczegolyZamowienia.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ZamowieniaController : SukkuShop.Areas.Admin.Controllers.ZamowieniaController
    {
        public T4MVC_ZamowieniaController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetOrdersListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetOrdersList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetOrdersList);
            GetOrdersListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangeOrderStateFromDetailsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int id, string value, string packageNumber);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ChangeOrderStateFromDetails(int id, string value, string packageNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ChangeOrderStateFromDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "value", value);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "packageNumber", packageNumber);
            ChangeOrderStateFromDetailsOverride(callInfo, id, value, packageNumber);
            return callInfo;
        }

        [NonAction]
        partial void SzczegolyZamowieniaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult SzczegolyZamowienia(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SzczegolyZamowienia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SzczegolyZamowieniaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DownloadInvoiceOverride(T4MVC_System_Web_Mvc_FileResult callInfo);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadInvoice()
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadInvoice);
            DownloadInvoiceOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
