// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Areas.Admin.Controllers
{
    public partial class KlienciController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected KlienciController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SetDiscount()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetDiscount);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public KlienciController Actions { get { return MVC.Admin.Klienci; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Klienci";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Klienci";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Lista = "Lista";
            public readonly string GetUserList = "GetUserList";
            public readonly string SetDiscount = "SetDiscount";
            public readonly string Szczegóły = "Szczegóły";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Lista = "Lista";
            public const string GetUserList = "GetUserList";
            public const string SetDiscount = "SetDiscount";
            public const string Szczegóły = "Szczegóły";
        }


        static readonly ActionParamsClass_SetDiscount s_params_SetDiscount = new ActionParamsClass_SetDiscount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetDiscount SetDiscountParams { get { return s_params_SetDiscount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetDiscount
        {
            public readonly string id = "id";
            public readonly string rabat = "rabat";
        }
        static readonly ActionParamsClass_Szczegóły s_params_Szczegóły = new ActionParamsClass_Szczegóły();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Szczegóły SzczegółyParams { get { return s_params_Szczegóły; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Szczegóły
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Lista = "Lista";
                public readonly string Szczegóły = "Szczegóły";
            }
            public readonly string Lista = "~/Areas/Admin/Views/Klienci/Lista.cshtml";
            public readonly string Szczegóły = "~/Areas/Admin/Views/Klienci/Szczegóły.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_KlienciController : SukkuShop.Areas.Admin.Controllers.KlienciController
    {
        public T4MVC_KlienciController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ListaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Lista()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lista);
            ListaOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetUserListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetUserList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetUserList);
            GetUserListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SetDiscountOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id, int rabat);

        [NonAction]
        public override System.Web.Mvc.JsonResult SetDiscount(int id, int rabat)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetDiscount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rabat", rabat);
            SetDiscountOverride(callInfo, id, rabat);
            return callInfo;
        }

        [NonAction]
        partial void SzczegółyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Szczegóły(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Szczegóły);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SzczegółyOverride(callInfo, id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
