// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Areas.Admin.Controllers
{
    public partial class PodkategorieController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PodkategorieController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AddSubCategory()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddSubCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult EditCategoryName()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditCategoryName);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult EditCategoryDiscount()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditCategoryDiscount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteSubCategory()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteSubCategory);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PodkategorieController Actions { get { return MVC.Admin.Podkategorie; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Podkategorie";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Podkategorie";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetCategoriesList = "GetCategoriesList";
            public readonly string AddSubCategory = "AddSubCategory";
            public readonly string EditCategoryName = "EditCategoryName";
            public readonly string EditCategoryDiscount = "EditCategoryDiscount";
            public readonly string DeleteSubCategory = "DeleteSubCategory";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetCategoriesList = "GetCategoriesList";
            public const string AddSubCategory = "AddSubCategory";
            public const string EditCategoryName = "EditCategoryName";
            public const string EditCategoryDiscount = "EditCategoryDiscount";
            public const string DeleteSubCategory = "DeleteSubCategory";
        }


        static readonly ActionParamsClass_AddSubCategory s_params_AddSubCategory = new ActionParamsClass_AddSubCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddSubCategory AddSubCategoryParams { get { return s_params_AddSubCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddSubCategory
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditCategoryName s_params_EditCategoryName = new ActionParamsClass_EditCategoryName();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditCategoryName EditCategoryNameParams { get { return s_params_EditCategoryName; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditCategoryName
        {
            public readonly string name = "name";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditCategoryDiscount s_params_EditCategoryDiscount = new ActionParamsClass_EditCategoryDiscount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditCategoryDiscount EditCategoryDiscountParams { get { return s_params_EditCategoryDiscount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditCategoryDiscount
        {
            public readonly string discount = "discount";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteSubCategory s_params_DeleteSubCategory = new ActionParamsClass_DeleteSubCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteSubCategory DeleteSubCategoryParams { get { return s_params_DeleteSubCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteSubCategory
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Areas/Admin/Views/Podkategorie/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PodkategorieController : SukkuShop.Areas.Admin.Controllers.PodkategorieController
    {
        public T4MVC_PodkategorieController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetCategoriesListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCategoriesList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCategoriesList);
            GetCategoriesListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddSubCategoryOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, SukkuShop.Areas.Admin.Models.SubcategoryCreateModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddSubCategory(SukkuShop.Areas.Admin.Models.SubcategoryCreateModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddSubCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddSubCategoryOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditCategoryNameOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string name, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult EditCategoryName(string name, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditCategoryName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditCategoryNameOverride(callInfo, name, id);
            return callInfo;
        }

        [NonAction]
        partial void EditCategoryDiscountOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string discount, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult EditCategoryDiscount(string discount, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EditCategoryDiscount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "discount", discount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditCategoryDiscountOverride(callInfo, discount, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteSubCategoryOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteSubCategory(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteSubCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteSubCategoryOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
