// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Threading.Tasks;
using System.Web.Mvc;
using T4MVC;
namespace SukkuShop.Controllers
{
    public partial class KontoController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected KontoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Zaloguj()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Zaloguj);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Aktywacja()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Aktywacja);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetujHaslo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetujHaslo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public KontoController Actions { get { return MVC.Konto; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Konto";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Konto";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Zaloguj = "Zaloguj";
            public readonly string Zarejestruj = "Zarejestruj";
            public readonly string Aktywacja = "Aktywacja";
            public readonly string ZapomnianeHaslo = "ZapomnianeHaslo";
            public readonly string ZapomnianeHasloPotwierdzenie = "ZapomnianeHasloPotwierdzenie";
            public readonly string ResetujHaslo = "ResetujHaslo";
            public readonly string ResetujHasloPotwierdzenie = "ResetujHasloPotwierdzenie";
            public readonly string Wyloguj = "Wyloguj";
            public readonly string EdytujDane = "EdytujDane";
            public readonly string Index = "Index";
            public readonly string ZmienHaslo = "ZmienHaslo";
            public readonly string UstawHaslo = "UstawHaslo";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Zaloguj = "Zaloguj";
            public const string Zarejestruj = "Zarejestruj";
            public const string Aktywacja = "Aktywacja";
            public const string ZapomnianeHaslo = "ZapomnianeHaslo";
            public const string ZapomnianeHasloPotwierdzenie = "ZapomnianeHasloPotwierdzenie";
            public const string ResetujHaslo = "ResetujHaslo";
            public const string ResetujHasloPotwierdzenie = "ResetujHasloPotwierdzenie";
            public const string Wyloguj = "Wyloguj";
            public const string EdytujDane = "EdytujDane";
            public const string Index = "Index";
            public const string ZmienHaslo = "ZmienHaslo";
            public const string UstawHaslo = "UstawHaslo";
        }


        static readonly ActionParamsClass_Zaloguj s_params_Zaloguj = new ActionParamsClass_Zaloguj();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Zaloguj ZalogujParams { get { return s_params_Zaloguj; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Zaloguj
        {
            public readonly string returnUrl = "returnUrl";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Zarejestruj s_params_Zarejestruj = new ActionParamsClass_Zarejestruj();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Zarejestruj ZarejestrujParams { get { return s_params_Zarejestruj; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Zarejestruj
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Aktywacja s_params_Aktywacja = new ActionParamsClass_Aktywacja();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Aktywacja AktywacjaParams { get { return s_params_Aktywacja; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Aktywacja
        {
            public readonly string userId = "userId";
            public readonly string code = "code";
        }
        static readonly ActionParamsClass_ZapomnianeHaslo s_params_ZapomnianeHaslo = new ActionParamsClass_ZapomnianeHaslo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ZapomnianeHaslo ZapomnianeHasloParams { get { return s_params_ZapomnianeHaslo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ZapomnianeHaslo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ResetujHaslo s_params_ResetujHaslo = new ActionParamsClass_ResetujHaslo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetujHaslo ResetujHasloParams { get { return s_params_ResetujHaslo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetujHaslo
        {
            public readonly string code = "code";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EdytujDane s_params_EdytujDane = new ActionParamsClass_EdytujDane();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EdytujDane EdytujDaneParams { get { return s_params_EdytujDane; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EdytujDane
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string message = "message";
        }
        static readonly ActionParamsClass_ZmienHaslo s_params_ZmienHaslo = new ActionParamsClass_ZmienHaslo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ZmienHaslo ZmienHasloParams { get { return s_params_ZmienHaslo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ZmienHaslo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_UstawHaslo s_params_UstawHaslo = new ActionParamsClass_UstawHaslo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UstawHaslo UstawHasloParams { get { return s_params_UstawHaslo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UstawHaslo
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EdytujDane = "EdytujDane";
                public readonly string Index = "Index";
                public readonly string ResetujHaslo = "ResetujHaslo";
                public readonly string ResetujHasloPotwierdzenie = "ResetujHasloPotwierdzenie";
                public readonly string UstawHaslo = "UstawHaslo";
                public readonly string Zaloguj = "Zaloguj";
                public readonly string ZapomnianeHaslo = "ZapomnianeHaslo";
                public readonly string ZapomnianeHasloPotwierdzenie = "ZapomnianeHasloPotwierdzenie";
                public readonly string Zarejestruj = "Zarejestruj";
                public readonly string ZmienHaslo = "ZmienHaslo";
            }
            public readonly string EdytujDane = "~/Views/Konto/EdytujDane.cshtml";
            public readonly string Index = "~/Views/Konto/Index.cshtml";
            public readonly string ResetujHaslo = "~/Views/Konto/ResetujHaslo.cshtml";
            public readonly string ResetujHasloPotwierdzenie = "~/Views/Konto/ResetujHasloPotwierdzenie.cshtml";
            public readonly string UstawHaslo = "~/Views/Konto/UstawHaslo.cshtml";
            public readonly string Zaloguj = "~/Views/Konto/Zaloguj.cshtml";
            public readonly string ZapomnianeHaslo = "~/Views/Konto/ZapomnianeHaslo.cshtml";
            public readonly string ZapomnianeHasloPotwierdzenie = "~/Views/Konto/ZapomnianeHasloPotwierdzenie.cshtml";
            public readonly string Zarejestruj = "~/Views/Konto/Zarejestruj.cshtml";
            public readonly string ZmienHaslo = "~/Views/Konto/ZmienHaslo.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_KontoController : SukkuShop.Controllers.KontoController
    {
        public T4MVC_KontoController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ZalogujOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Zaloguj(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Zaloguj);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            ZalogujOverride(callInfo, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void ZalogujOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Models.LoginViewModel model, string returnUrl);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Zaloguj(SukkuShop.Models.LoginViewModel model, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Zaloguj);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            ZalogujOverride(callInfo, model, returnUrl);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ZarejestrujOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Zarejestruj()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Zarejestruj);
            ZarejestrujOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ZarejestrujOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Models.RegisterViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Zarejestruj(SukkuShop.Models.RegisterViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Zarejestruj);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ZarejestrujOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void AktywacjaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int userId, string code);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Aktywacja(int userId, string code)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Aktywacja);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            AktywacjaOverride(callInfo, userId, code);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ZapomnianeHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ZapomnianeHaslo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ZapomnianeHaslo);
            ZapomnianeHasloOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ZapomnianeHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Models.ForgotPasswordViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ZapomnianeHaslo(SukkuShop.Models.ForgotPasswordViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ZapomnianeHaslo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ZapomnianeHasloOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ZapomnianeHasloPotwierdzenieOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ZapomnianeHasloPotwierdzenie()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ZapomnianeHasloPotwierdzenie);
            ZapomnianeHasloPotwierdzenieOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ResetujHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string code);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetujHaslo(string code)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetujHaslo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            ResetujHasloOverride(callInfo, code);
            return callInfo;
        }

        [NonAction]
        partial void ResetujHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Models.ResetPasswordViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResetujHaslo(SukkuShop.Models.ResetPasswordViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetujHaslo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ResetujHasloOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ResetujHasloPotwierdzenieOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetujHasloPotwierdzenie()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetujHasloPotwierdzenie);
            ResetujHasloPotwierdzenieOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void WylogujOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Wyloguj()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Wyloguj);
            WylogujOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EdytujDaneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> EdytujDane()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EdytujDane);
            EdytujDaneOverride(callInfo);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void EdytujDaneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Models.ChangeUserInfoViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> EdytujDane(SukkuShop.Models.ChangeUserInfoViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EdytujDane);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EdytujDaneOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Controllers.KontoController.ManageMessageId? message);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Index(SukkuShop.Controllers.KontoController.ManageMessageId? message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            IndexOverride(callInfo, message);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ZmienHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ZmienHaslo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ZmienHaslo);
            ZmienHasloOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ZmienHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Models.ChangePasswordViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ZmienHaslo(SukkuShop.Models.ChangePasswordViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ZmienHaslo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ZmienHasloOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void UstawHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UstawHaslo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UstawHaslo);
            UstawHasloOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UstawHasloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SukkuShop.Models.SetPasswordViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> UstawHaslo(SukkuShop.Models.SetPasswordViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UstawHaslo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            UstawHasloOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
