// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance

using SukkuShop.Models;
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Controllers
{
    public partial class NavController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected NavController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult SortList()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SortList);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public NavController Actions { get { return MVC.Nav; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Nav";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Nav";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Menu = "Menu";
            public readonly string SubCategory = "SubCategory";
            public readonly string SortList = "SortList";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Menu = "Menu";
            public const string SubCategory = "SubCategory";
            public const string SortList = "SortList";
        }


        static readonly ActionParamsClass_Menu s_params_Menu = new ActionParamsClass_Menu();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Menu MenuParams { get { return s_params_Menu; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Menu
        {
            public readonly string category = "category";
        }
        static readonly ActionParamsClass_SubCategory s_params_SubCategory = new ActionParamsClass_SubCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubCategory SubCategoryParams { get { return s_params_SubCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubCategory
        {
            public readonly string category = "category";
            public readonly string subcategory = "subcategory";
            public readonly string method = "method";
        }
        static readonly ActionParamsClass_SortList s_params_SortList = new ActionParamsClass_SortList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SortList SortListParams { get { return s_params_SortList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SortList
        {
            public readonly string category = "category";
            public readonly string search = "search";
            public readonly string subcategory = "subcategory";
            public readonly string method = "method";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Menu = "Menu";
                public readonly string SearchSortList = "SearchSortList";
                public readonly string SortList = "SortList";
                public readonly string SubCategory = "SubCategory";
            }
            public readonly string Menu = "~/Views/Nav/Menu.cshtml";
            public readonly string SearchSortList = "~/Views/Nav/SearchSortList.cshtml";
            public readonly string SortList = "~/Views/Nav/SortList.cshtml";
            public readonly string SubCategory = "~/Views/Nav/SubCategory.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_NavController : SukkuShop.Controllers.NavController
    {
        public T4MVC_NavController() : base(Dummy.Instance) { }

        [NonAction]
        partial void MenuOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string category);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Menu(string category,SortMethod method)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Menu);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "method", method);
            MenuOverride(callInfo, category);
            return callInfo;
        }

        [NonAction]
        partial void SubCategoryOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string category, string subcategory, SukkuShop.Models.SortMethod method);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SubCategory(string category, string subcategory, SukkuShop.Models.SortMethod method)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SubCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "subcategory", subcategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "method", method);
            SubCategoryOverride(callInfo, category, subcategory, method);
            return callInfo;
        }

        [NonAction]
        partial void SortListOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string category, string search, string subcategory, SukkuShop.Models.SortMethod method);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SortList(string category, string search, string subcategory, SukkuShop.Models.SortMethod method)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SortList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "subcategory", subcategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "method", method);
            SortListOverride(callInfo, category, search, subcategory, method);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
