// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SukkuShop.Controllers
{
    public partial class SklepController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SklepController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProductByCategory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProductByCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Produkty()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Produkty);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SzczegółyProduktu()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SzczegółyProduktu);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Wyszukaj()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Wyszukaj);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RedirectToLocal()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectToLocal);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SklepController Actions { get { return MVC.Sklep; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Sklep";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Sklep";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetProductByCategory = "GetProductByCategory";
            public readonly string Produkty = "Produkty";
            public readonly string SzczegółyProduktu = "SzczegółyProduktu";
            public readonly string Wyszukaj = "Wyszukaj";
            public readonly string Szukaj = "Szukaj";
            public readonly string RedirectToLocal = "RedirectToLocal";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetProductByCategory = "GetProductByCategory";
            public const string Produkty = "Produkty";
            public const string SzczegółyProduktu = "SzczegółyProduktu";
            public const string Wyszukaj = "Wyszukaj";
            public const string Szukaj = "Szukaj";
            public const string RedirectToLocal = "RedirectToLocal";
        }


        static readonly ActionParamsClass_GetProductByCategory s_params_GetProductByCategory = new ActionParamsClass_GetProductByCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProductByCategory GetProductByCategoryParams { get { return s_params_GetProductByCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProductByCategory
        {
            public readonly string category = "category";
        }
        static readonly ActionParamsClass_Produkty s_params_Produkty = new ActionParamsClass_Produkty();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Produkty ProduktyParams { get { return s_params_Produkty; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Produkty
        {
            public readonly string category = "category";
        }
        static readonly ActionParamsClass_SzczegółyProduktu s_params_SzczegółyProduktu = new ActionParamsClass_SzczegółyProduktu();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SzczegółyProduktu SzczegółyProduktuParams { get { return s_params_SzczegółyProduktu; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SzczegółyProduktu
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Wyszukaj s_params_Wyszukaj = new ActionParamsClass_Wyszukaj();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Wyszukaj WyszukajParams { get { return s_params_Wyszukaj; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Wyszukaj
        {
            public readonly string search = "search";
            public readonly string method = "method";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_RedirectToLocal s_params_RedirectToLocal = new ActionParamsClass_RedirectToLocal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedirectToLocal RedirectToLocalParams { get { return s_params_RedirectToLocal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedirectToLocal
        {
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string NoProducts = "NoProducts";
                public readonly string ProductItem = "ProductItem";
                public readonly string Produkty = "Produkty";
                public readonly string similarProduct = "similarProduct";
                public readonly string SzczegółyProduktu = "SzczegółyProduktu";
            }
            public readonly string NoProducts = "~/Views/Sklep/NoProducts.cshtml";
            public readonly string ProductItem = "~/Views/Sklep/ProductItem.cshtml";
            public readonly string Produkty = "~/Views/Sklep/Produkty.cshtml";
            public readonly string similarProduct = "~/Views/Sklep/similarProduct.cshtml";
            public readonly string SzczegółyProduktu = "~/Views/Sklep/SzczegółyProduktu.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SklepController : SukkuShop.Controllers.SklepController
    {
        public T4MVC_SklepController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetProductByCategoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string category);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProductByCategory(string category)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProductByCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            GetProductByCategoryOverride(callInfo, category);
            return callInfo;
        }

        [NonAction]
        partial void ProduktyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string category);

        [NonAction]
        public override System.Web.Mvc.ActionResult Produkty(string category)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Produkty);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "category", category);
            ProduktyOverride(callInfo, category);
            return callInfo;
        }

        [NonAction]
        partial void SzczegółyProduktuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult SzczegółyProduktu(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SzczegółyProduktu);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SzczegółyProduktuOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void WyszukajOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string search, SukkuShop.Models.SortMethod method, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Wyszukaj(string search, SukkuShop.Models.SortMethod method, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Wyszukaj);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "method", method);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            WyszukajOverride(callInfo, search, method, page);
            return callInfo;
        }

        [NonAction]
        partial void SzukajOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Szukaj()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Szukaj);
            SzukajOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToLocalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult RedirectToLocal(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectToLocal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            RedirectToLocalOverride(callInfo, returnUrl);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
