// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly AdminClass s_Admin = new AdminClass();
    public static AdminClass Admin { get { return s_Admin; } }
    public static SukkuShop.Controllers.ErrorController Error = new SukkuShop.Controllers.T4MVC_ErrorController();
    public static SukkuShop.Controllers.HomeController Home = new SukkuShop.Controllers.T4MVC_HomeController();
    public static SukkuShop.Controllers.KontoController Konto = new SukkuShop.Controllers.T4MVC_KontoController();
    public static SukkuShop.Controllers.KoszykController Koszyk = new SukkuShop.Controllers.T4MVC_KoszykController();
    public static SukkuShop.Controllers.NavController Nav = new SukkuShop.Controllers.T4MVC_NavController();
    public static SukkuShop.Controllers.PreviewController Preview = new SukkuShop.Controllers.T4MVC_PreviewController();
    public static SukkuShop.Controllers.SklepController Sklep = new SukkuShop.Controllers.T4MVC_SklepController();
    public static SukkuShop.Controllers.ZamowienieController Zamowienie = new SukkuShop.Controllers.T4MVC_ZamowienieController();
    public static T4MVC.EmailsController Emails = new T4MVC.EmailsController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdminClass
    {
        public readonly string Name = "Admin";
        public SukkuShop.Areas.Admin.Controllers.ContentController Content = new SukkuShop.Areas.Admin.Controllers.T4MVC_ContentController();
        public SukkuShop.Areas.Admin.Controllers.KlienciController Klienci = new SukkuShop.Areas.Admin.Controllers.T4MVC_KlienciController();
        public SukkuShop.Areas.Admin.Controllers.ProduktyController Produkty = new SukkuShop.Areas.Admin.Controllers.T4MVC_ProduktyController();
        public SukkuShop.Areas.Admin.Controllers.StatystykiController Statystyki = new SukkuShop.Areas.Admin.Controllers.T4MVC_StatystykiController();
        public SukkuShop.Areas.Admin.Controllers.ZamowieniaController Zamowienia = new SukkuShop.Areas.Admin.Controllers.T4MVC_ZamowieniaController();
        public T4MVC.Admin.SharedController Shared = new T4MVC.Admin.SharedController();
    }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ViewResult : System.Web.Mvc.ViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_PartialViewResult : System.Web.Mvc.PartialViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_PartialViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileResult : System.Web.Mvc.FileResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileResult(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    protected override void WriteFile(System.Web.HttpResponseBase response) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string AccSzczegZam_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AccSzczegZam.min.js") ? Url("AccSzczegZam.min.js") : Url("AccSzczegZam.js");
        public static readonly string AccSzczegZam_min_js = Url("AccSzczegZam.min.js");
        public static readonly string AccSzczegZam_min_js_map = Url("AccSzczegZam.min.js.map");
        public static readonly string angular_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular.min.js") ? Url("angular.min.js") : Url("angular.js");
        public static readonly string angular_min_js = Url("angular.min.js");
        public static readonly string angular_min_js_map = Url("angular.min.js.map");
        public static readonly string CartSummary_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/CartSummary.min.js") ? Url("CartSummary.min.js") : Url("CartSummary.js");
        public static readonly string CartSummary_min_js = Url("CartSummary.min.js");
        public static readonly string CartSummary_min_js_map = Url("CartSummary.min.js.map");
        public static readonly string Chart_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Chart.min.js") ? Url("Chart.min.js") : Url("Chart.js");
        public static readonly string Chart_min_js = Url("Chart.min.js");
        public static readonly string jquery_2_1_1_min_js = Url("jquery-2.1.1.min.js");
        public static readonly string jquery_2_1_1_min_js_map = Url("jquery-2.1.1.min.js.map");
        public static readonly string jquery_2_1_3_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.3.intellisense.min.js") ? Url("jquery-2.1.3.intellisense.min.js") : Url("jquery-2.1.3.intellisense.js");
        public static readonly string jquery_2_1_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.3.min.js") ? Url("jquery-2.1.3.min.js") : Url("jquery-2.1.3.js");
        public static readonly string jquery_2_1_3_min_js = Url("jquery-2.1.3.min.js");
        public static readonly string jquery_2_1_3_min_map = Url("jquery-2.1.3.min.map");
        public static readonly string jquery_ui_1_11_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.11.3.min.js") ? Url("jquery-ui-1.11.3.min.js") : Url("jquery-ui-1.11.3.js");
        public static readonly string jquery_ui_1_11_3_min_js = Url("jquery-ui-1.11.3.min.js");
        public static readonly string jquery_ui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.js") ? Url("jquery-ui.min.js") : Url("jquery-ui.js");
        public static readonly string jquery_ui_min_js = Url("jquery-ui.min.js");
        public static readonly string jquery_elevatezoom_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.elevatezoom.min.js") ? Url("jquery.elevatezoom.min.js") : Url("jquery.elevatezoom.js");
        public static readonly string jquery_elevatezoom_min_js = Url("jquery.elevatezoom.min.js");
        public static readonly string jquery_elevatezoom_min_js_map = Url("jquery.elevatezoom.min.js.map");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jquery_unobtrusive_ajax_min_js_map = Url("jquery.unobtrusive-ajax.min.js.map");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_min_js_map = Url("jquery.validate.min.js.map");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string jquery_validate_unobtrusive_min_js_map = Url("jquery.validate.unobtrusive.min.js.map");
        public static readonly string Konto_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Konto.min.js") ? Url("Konto.min.js") : Url("Konto.js");
        public static readonly string Konto_min_js = Url("Konto.min.js");
        public static readonly string Konto_min_js_map = Url("Konto.min.js.map");
        public static readonly string KontoNieaktywne_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/KontoNieaktywne.min.js") ? Url("KontoNieaktywne.min.js") : Url("KontoNieaktywne.js");
        public static readonly string KontoNieaktywne_min_js = Url("KontoNieaktywne.min.js");
        public static readonly string KontoNieaktywne_min_js_map = Url("KontoNieaktywne.min.js.map");
        public static readonly string Login_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Login.min.js") ? Url("Login.min.js") : Url("Login.js");
        public static readonly string Login_min_js = Url("Login.min.js");
        public static readonly string Login_min_js_map = Url("Login.min.js.map");
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        public static readonly string modernizr_2_8_3_min_js = Url("modernizr-2.8.3.min.js");
        public static readonly string modernizr_2_8_3_min_js_map = Url("modernizr-2.8.3.min.js.map");
        public static readonly string OrderKrok1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OrderKrok1.min.js") ? Url("OrderKrok1.min.js") : Url("OrderKrok1.js");
        public static readonly string OrderKrok1_min_js = Url("OrderKrok1.min.js");
        public static readonly string OrderKrok1_min_js_map = Url("OrderKrok1.min.js.map");
        public static readonly string OrderKrok2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OrderKrok2.min.js") ? Url("OrderKrok2.min.js") : Url("OrderKrok2.js");
        public static readonly string OrderKrok2_min_js = Url("OrderKrok2.min.js");
        public static readonly string OrderKrok2_min_js_map = Url("OrderKrok2.min.js.map");
        public static readonly string podsumowanie_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/podsumowanie.min.js") ? Url("podsumowanie.min.js") : Url("podsumowanie.js");
        public static readonly string podsumowanie_min_js = Url("podsumowanie.min.js");
        public static readonly string podsumowanie_min_js_map = Url("podsumowanie.min.js.map");
        public static readonly string Register_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Register.min.js") ? Url("Register.min.js") : Url("Register.js");
        public static readonly string Register_min_js = Url("Register.min.js");
        public static readonly string Register_min_js_map = Url("Register.min.js.map");
        public static readonly string Resetuj_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Resetuj.min.js") ? Url("Resetuj.min.js") : Url("Resetuj.js");
        public static readonly string Resetuj_min_js = Url("Resetuj.min.js");
        public static readonly string Resetuj_min_js_map = Url("Resetuj.min.js.map");
        public static readonly string shopAngular_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/shopAngular.min.js") ? Url("shopAngular.min.js") : Url("shopAngular.js");
        public static readonly string shopAngular_min_js = Url("shopAngular.min.js");
        public static readonly string shopAngular_min_js_map = Url("shopAngular.min.js.map");
        public static readonly string shopdetails_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/shopdetails.min.js") ? Url("shopdetails.min.js") : Url("shopdetails.js");
        public static readonly string shopdetails_min_js = Url("shopdetails.min.js");
        public static readonly string shopdetails_min_js_map = Url("shopdetails.min.js.map");
        public static readonly string ZapomnianeHaslo_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ZapomnianeHaslo.min.js") ? Url("ZapomnianeHaslo.min.js") : Url("ZapomnianeHaslo.js");
        public static readonly string ZapomnianeHaslo_min_js = Url("ZapomnianeHaslo.min.js");
        public static readonly string ZapomnianeHaslo_min_js_map = Url("ZapomnianeHaslo.min.js.map");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class css {
            private const string URLPATH = "~/Content/css";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Error {
                private const string URLPATH = "~/Content/css/Error";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Error_scss = Url("Error.scss");
                public static readonly string Error_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Error.min.css") ? Url("Error.min.css") : Url("Error.css");
                     
                public static readonly string Error_css_map = Url("Error.css.map");
                public static readonly string Error_min_css = Url("Error.min.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Home {
                private const string URLPATH = "~/Content/css/Home";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Home_scss = Url("Home.scss");
                public static readonly string Home_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Home.min.css") ? Url("Home.min.css") : Url("Home.css");
                     
                public static readonly string Home_css_map = Url("Home.css.map");
                public static readonly string Home_min_css = Url("Home.min.css");
            }
        
            public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                 
            public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
            public static readonly string jquery_ui_structure_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.structure.min.css") ? Url("jquery-ui.structure.min.css") : Url("jquery-ui.structure.css");
                 
            public static readonly string jquery_ui_structure_min_css = Url("jquery-ui.structure.min.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Konto {
                private const string URLPATH = "~/Content/css/Konto";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Details_scss = Url("Details.scss");
                public static readonly string Details_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Details.min.css") ? Url("Details.min.css") : Url("Details.css");
                     
                public static readonly string Details_css_map = Url("Details.css.map");
                public static readonly string Details_min_css = Url("Details.min.css");
                public static readonly string KontoNieaktywne_scss = Url("KontoNieaktywne.scss");
                public static readonly string KontoNieaktywne_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/KontoNieaktywne.min.css") ? Url("KontoNieaktywne.min.css") : Url("KontoNieaktywne.css");
                     
                public static readonly string KontoNieaktywne_css_map = Url("KontoNieaktywne.css.map");
                public static readonly string KontoNieaktywne_min_css = Url("KontoNieaktywne.min.css");
                public static readonly string Login_scss = Url("Login.scss");
                public static readonly string Login_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Login.min.css") ? Url("Login.min.css") : Url("Login.css");
                     
                public static readonly string Login_css_map = Url("Login.css.map");
                public static readonly string Login_min_css = Url("Login.min.css");
                public static readonly string OrderHistory_scss = Url("OrderHistory.scss");
                public static readonly string OrderHistory_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OrderHistory.min.css") ? Url("OrderHistory.min.css") : Url("OrderHistory.css");
                     
                public static readonly string OrderHistory_css_map = Url("OrderHistory.css.map");
                public static readonly string OrderHistory_min_css = Url("OrderHistory.min.css");
                public static readonly string OrderPreview_scss = Url("OrderPreview.scss");
                public static readonly string OrderPreview_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OrderPreview.min.css") ? Url("OrderPreview.min.css") : Url("OrderPreview.css");
                     
                public static readonly string OrderPreview_css_map = Url("OrderPreview.css.map");
                public static readonly string OrderPreview_min_css = Url("OrderPreview.min.css");
                public static readonly string Register_scss = Url("Register.scss");
                public static readonly string Register_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Register.min.css") ? Url("Register.min.css") : Url("Register.css");
                     
                public static readonly string Register_css_map = Url("Register.css.map");
                public static readonly string Register_min_css = Url("Register.min.css");
                public static readonly string RegisterSuccess_scss = Url("RegisterSuccess.scss");
                public static readonly string RegisterSuccess_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/RegisterSuccess.min.css") ? Url("RegisterSuccess.min.css") : Url("RegisterSuccess.css");
                     
                public static readonly string RegisterSuccess_css_map = Url("RegisterSuccess.css.map");
                public static readonly string RegisterSuccess_min_css = Url("RegisterSuccess.min.css");
                public static readonly string Resetuj_scss = Url("Resetuj.scss");
                public static readonly string Resetuj_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Resetuj.min.css") ? Url("Resetuj.min.css") : Url("Resetuj.css");
                     
                public static readonly string Resetuj_css_map = Url("Resetuj.css.map");
                public static readonly string Resetuj_min_css = Url("Resetuj.min.css");
                public static readonly string ZapomnianeHaslo_scss = Url("ZapomnianeHaslo.scss");
                public static readonly string ZapomnianeHaslo_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ZapomnianeHaslo.min.css") ? Url("ZapomnianeHaslo.min.css") : Url("ZapomnianeHaslo.css");
                     
                public static readonly string ZapomnianeHaslo_css_map = Url("ZapomnianeHaslo.css.map");
                public static readonly string ZapomnianeHaslo_min_css = Url("ZapomnianeHaslo.min.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Koszyk {
                private const string URLPATH = "~/Content/css/Koszyk";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Cart_scss = Url("Cart.scss");
                public static readonly string Cart_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Cart.min.css") ? Url("Cart.min.css") : Url("Cart.css");
                     
                public static readonly string Cart_css_map = Url("Cart.css.map");
                public static readonly string Cart_min_css = Url("Cart.min.css");
            }
        
            public static readonly string main_scss = Url("main.scss");
            public static readonly string main_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/main.min.css") ? Url("main.min.css") : Url("main.css");
                 
            public static readonly string main_css_map = Url("main.css.map");
            public static readonly string main_min_css = Url("main.min.css");
            public static readonly string reset_scss = Url("reset.scss");
            public static readonly string reset_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/reset.min.css") ? Url("reset.min.css") : Url("reset.css");
                 
            public static readonly string reset_css_map = Url("reset.css.map");
            public static readonly string reset_min_css = Url("reset.min.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Sklep {
                private const string URLPATH = "~/Content/css/Sklep";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Shop_scss = Url("Shop.scss");
                public static readonly string Shop_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Shop.min.css") ? Url("Shop.min.css") : Url("Shop.css");
                     
                public static readonly string Shop_css_map = Url("Shop.css.map");
                public static readonly string Shop_min_css = Url("Shop.min.css");
                public static readonly string ShopDetails_scss = Url("ShopDetails.scss");
                public static readonly string ShopDetails_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ShopDetails.min.css") ? Url("ShopDetails.min.css") : Url("ShopDetails.css");
                     
                public static readonly string ShopDetails_css_map = Url("ShopDetails.css.map");
                public static readonly string ShopDetails_min_css = Url("ShopDetails.min.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Zamowienie {
                private const string URLPATH = "~/Content/css/Zamowienie";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string ClientData_scss = Url("ClientData.scss");
                public static readonly string ClientData_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ClientData.min.css") ? Url("ClientData.min.css") : Url("ClientData.css");
                     
                public static readonly string ClientData_css_map = Url("ClientData.css.map");
                public static readonly string ClientData_min_css = Url("ClientData.min.css");
                public static readonly string Krok1_scss = Url("Krok1.scss");
                public static readonly string Krok1_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Krok1.min.css") ? Url("Krok1.min.css") : Url("Krok1.css");
                     
                public static readonly string Krok1_css_map = Url("Krok1.css.map");
                public static readonly string Krok1_min_css = Url("Krok1.min.css");
                public static readonly string OrderSubmitted_scss = Url("OrderSubmitted.scss");
                public static readonly string OrderSubmitted_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OrderSubmitted.min.css") ? Url("OrderSubmitted.min.css") : Url("OrderSubmitted.css");
                     
                public static readonly string OrderSubmitted_css_map = Url("OrderSubmitted.css.map");
                public static readonly string OrderSubmitted_min_css = Url("OrderSubmitted.min.css");
                public static readonly string podsumowanie_scss = Url("podsumowanie.scss");
                public static readonly string podsumowanie_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/podsumowanie.min.css") ? Url("podsumowanie.min.css") : Url("podsumowanie.css");
                     
                public static readonly string podsumowanie_css_map = Url("podsumowanie.css.map");
                public static readonly string podsumowanie_min_css = Url("podsumowanie.min.css");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            private const string URLPATH = "~/Content/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string FoglihtenPCS_068_eot = Url("FoglihtenPCS-068.eot");
            public static readonly string FoglihtenPCS_068_svg = Url("FoglihtenPCS-068.svg");
            public static readonly string FoglihtenPCS_068_ttf = Url("FoglihtenPCS-068.ttf");
            public static readonly string FoglihtenPCS_068_woff = Url("FoglihtenPCS-068.woff");
            public static readonly string FTLTLT_TTF = Url("FTLTLT.TTF");
            public static readonly string lucida_bright_eot = Url("lucida_bright.eot");
            public static readonly string lucida_bright_svg = Url("lucida_bright.svg");
            public static readonly string lucida_bright_ttf = Url("lucida_bright.ttf");
            public static readonly string lucida_bright_woff = Url("lucida_bright.woff");
            public static readonly string lucida_console_eot = Url("lucida_console.eot");
            public static readonly string lucida_console_svg = Url("lucida_console.svg");
            public static readonly string lucida_console_ttf = Url("lucida_console.ttf");
            public static readonly string lucida_console_woff = Url("lucida_console.woff");
            public static readonly string phagspa_ttf = Url("phagspa.ttf");
            public static readonly string SegoeSemibold_ttf = Url("SegoeSemibold.ttf");
            public static readonly string SegoeSemiboldIE_eot = Url("SegoeSemiboldIE.eot");
            public static readonly string segoeui_ttf = Url("segoeui.ttf");
            public static readonly string segoeuibold_ttf = Url("segoeuibold.ttf");
            public static readonly string SEGOEUIL_eot = Url("SEGOEUIL.eot");
            public static readonly string segoeuil_ttf = Url("segoeuil.ttf");
            public static readonly string SEGOEUIL_woff = Url("SEGOEUIL.woff");
            public static readonly string segoeuisl_ttf = Url("segoeuisl.ttf");
            public static readonly string seguibl_eot = Url("seguibl.eot");
            public static readonly string seguibl_ttf = Url("seguibl.ttf");
            public static readonly string seguibl_woff = Url("seguibl.woff");
            public static readonly string seguiblack_ttf = Url("seguiblack.ttf");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Images {
            private const string URLPATH = "~/Content/Images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string checkbox_nonactive_png = Url("checkbox-nonactive.png");
            public static readonly string checkbox_png = Url("checkbox.png");
            public static readonly string cinnamon_sticks_jpg = Url("cinnamon-sticks.jpg");
            public static readonly string content_pic1_jpg = Url("content-pic1.jpg");
            public static readonly string content_pic2_jpg = Url("content-pic2.jpg");
            public static readonly string content_pic3_jpg = Url("content-pic3.jpg");
            public static readonly string footer_cart_png = Url("footer-cart.png");
            public static readonly string footer_sukku_png = Url("footer-sukku.png");
            public static readonly string footer_user_png = Url("footer-user.png");
            public static readonly string logo_header_png = Url("logo-header.png");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Panels {
                private const string URLPATH = "~/Content/Images/Panels";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string eye_png = Url("eye.png");
                public static readonly string left_jpg = Url("left.jpg");
                public static readonly string pepper_jpg = Url("pepper.jpg");
            }
        
            public static readonly string processing_gif = Url("processing.gif");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Shop {
                private const string URLPATH = "~/Content/Images/Shop";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string _1_jpg = Url("1.jpg");
                public static readonly string _2_jpg = Url("2.jpg");
                public static readonly string _4_jpg = Url("4.jpg");
                public static readonly string bakalie_jpg = Url("bakalie.jpg");
                public static readonly string basket_png = Url("basket.png");
                public static readonly string carticon_png = Url("carticon.png");
                public static readonly string carticonwhite_png = Url("carticonwhite.png");
                public static readonly string herbaty_jpg = Url("herbaty.jpg");
                public static readonly string info_icon_png = Url("info_icon.png");
                public static readonly string inne_jpg = Url("inne.jpg");
                public static readonly string kosmetyki_jpg = Url("kosmetyki.jpg");
                public static readonly string lupa_png = Url("lupa.png");
                public static readonly string przyprawy_jpg = Url("przyprawy.jpg");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/accordion.min.css") ? Url("accordion.min.css") : Url("accordion.css");
                     
                public static readonly string all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/all.min.css") ? Url("all.min.css") : Url("all.css");
                     
                public static readonly string autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autocomplete.min.css") ? Url("autocomplete.min.css") : Url("autocomplete.css");
                     
                public static readonly string base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/base.min.css") ? Url("base.min.css") : Url("base.css");
                     
                public static readonly string button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/button.min.css") ? Url("button.min.css") : Url("button.css");
                     
                public static readonly string core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/core.min.css") ? Url("core.min.css") : Url("core.css");
                     
                public static readonly string datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/datepicker.min.css") ? Url("datepicker.min.css") : Url("datepicker.css");
                     
                public static readonly string dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dialog.min.css") ? Url("dialog.min.css") : Url("dialog.css");
                     
                public static readonly string draggable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/draggable.min.css") ? Url("draggable.min.css") : Url("draggable.css");
                     
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/menu.min.css") ? Url("menu.min.css") : Url("menu.css");
                     
                public static readonly string progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/progressbar.min.css") ? Url("progressbar.min.css") : Url("progressbar.css");
                     
                public static readonly string resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/resizable.min.css") ? Url("resizable.min.css") : Url("resizable.css");
                     
                public static readonly string selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectable.min.css") ? Url("selectable.min.css") : Url("selectable.css");
                     
                public static readonly string selectmenu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectmenu.min.css") ? Url("selectmenu.min.css") : Url("selectmenu.css");
                     
                public static readonly string slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/slider.min.css") ? Url("slider.min.css") : Url("slider.css");
                     
                public static readonly string sortable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sortable.min.css") ? Url("sortable.min.css") : Url("sortable.css");
                     
                public static readonly string spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/spinner.min.css") ? Url("spinner.min.css") : Url("spinner.css");
                     
                public static readonly string tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tabs.min.css") ? Url("tabs.min.css") : Url("tabs.css");
                     
                public static readonly string theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/theme.min.css") ? Url("theme.min.css") : Url("theme.css");
                     
                public static readonly string tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tooltip.min.css") ? Url("tooltip.min.css") : Url("tooltip.css");
                     
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class web {
            private const string URLPATH = "~/Content/web";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string DaneKlientaKoszyk_html = Url("DaneKlientaKoszyk.html");
            public static readonly string OrderDetails_html = Url("OrderDetails.html");
            public static readonly string OrderHistory_html = Url("OrderHistory.html");
            public static readonly string OrderPreview_html = Url("OrderPreview.html");
            public static readonly string OrderSummary_html = Url("OrderSummary.html");
        }
    
    }


    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Areas {
        private const string URLPATH = "~/Areas";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Admin {
            private const string URLPATH = "~/Areas/Admin";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Scripts {
                private const string URLPATH = "~/Areas/Admin/Scripts";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string AdminEditProduct_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AdminEditProduct.min.js") ? Url("AdminEditProduct.min.js") : Url("AdminEditProduct.js");
                public static readonly string AdminEditProduct_min_js = Url("AdminEditProduct.min.js");
                public static readonly string AdminEditProduct_min_js_map = Url("AdminEditProduct.min.js.map");
                public static readonly string AdminProduct_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AdminProduct.min.js") ? Url("AdminProduct.min.js") : Url("AdminProduct.js");
                public static readonly string AdminProduct_min_js = Url("AdminProduct.min.js");
                public static readonly string AdminProduct_min_js_map = Url("AdminProduct.min.js.map");
                public static readonly string ContentIndex_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ContentIndex.min.js") ? Url("ContentIndex.min.js") : Url("ContentIndex.js");
                public static readonly string ContentIndex_min_js = Url("ContentIndex.min.js");
                public static readonly string ContentIndex_min_js_map = Url("ContentIndex.min.js.map");
                public static readonly string ordersListAngular_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ordersListAngular.min.js") ? Url("ordersListAngular.min.js") : Url("ordersListAngular.js");
                public static readonly string ordersListAngular_min_js = Url("ordersListAngular.min.js");
                public static readonly string ordersListAngular_min_js_map = Url("ordersListAngular.min.js.map");
                public static readonly string productListAngular_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/productListAngular.min.js") ? Url("productListAngular.min.js") : Url("productListAngular.js");
                public static readonly string productListAngular_min_js = Url("productListAngular.min.js");
                public static readonly string productListAngular_min_js_map = Url("productListAngular.min.js.map");
                public static readonly string RegulaminEditor_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/RegulaminEditor.min.js") ? Url("RegulaminEditor.min.js") : Url("RegulaminEditor.js");
                public static readonly string RegulaminEditor_min_js = Url("RegulaminEditor.min.js");
                public static readonly string RegulaminEditor_min_js_map = Url("RegulaminEditor.min.js.map");
                public static readonly string StatisticsAdmin_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/StatisticsAdmin.min.js") ? Url("StatisticsAdmin.min.js") : Url("StatisticsAdmin.js");
                public static readonly string StatisticsAdmin_min_js = Url("StatisticsAdmin.min.js");
                public static readonly string StatisticsAdmin_min_js_map = Url("StatisticsAdmin.min.js.map");
                public static readonly string userDetails_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/userDetails.min.js") ? Url("userDetails.min.js") : Url("userDetails.js");
                public static readonly string userDetails_min_js = Url("userDetails.min.js");
                public static readonly string userDetails_min_js_map = Url("userDetails.min.js.map");
                public static readonly string userListAngular_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/userListAngular.min.js") ? Url("userListAngular.min.js") : Url("userListAngular.js");
                public static readonly string userListAngular_min_js = Url("userListAngular.min.js");
                public static readonly string userListAngular_min_js_map = Url("userListAngular.min.js.map");
            }
        
        }
    }

    public static partial class Areas {
    
        public static partial class Admin {
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Content {
                private const string URLPATH = "~/Areas/Admin/Content";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class css {
                    private const string URLPATH = "~/Areas/Admin/Content/css";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string AdminOrdersList_scss = Url("AdminOrdersList.scss");
                    public static readonly string AdminOrdersList_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AdminOrdersList.min.css") ? Url("AdminOrdersList.min.css") : Url("AdminOrdersList.css");
                         
                    public static readonly string AdminOrdersList_css_map = Url("AdminOrdersList.css.map");
                    public static readonly string AdminOrdersList_min_css = Url("AdminOrdersList.min.css");
                    public static readonly string AdminProductsList_scss = Url("AdminProductsList.scss");
                    public static readonly string AdminProductsList_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AdminProductsList.min.css") ? Url("AdminProductsList.min.css") : Url("AdminProductsList.css");
                         
                    public static readonly string AdminProductsList_css_map = Url("AdminProductsList.css.map");
                    public static readonly string AdminProductsList_min_css = Url("AdminProductsList.min.css");
                    public static readonly string AdminUserList_scss = Url("AdminUserList.scss");
                    public static readonly string AdminUserList_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AdminUserList.min.css") ? Url("AdminUserList.min.css") : Url("AdminUserList.css");
                         
                    public static readonly string AdminUserList_css_map = Url("AdminUserList.css.map");
                    public static readonly string AdminUserList_min_css = Url("AdminUserList.min.css");
                    public static readonly string ContentIndex_scss = Url("ContentIndex.scss");
                    public static readonly string ContentIndex_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ContentIndex.min.css") ? Url("ContentIndex.min.css") : Url("ContentIndex.css");
                         
                    public static readonly string ContentIndex_css_map = Url("ContentIndex.css.map");
                    public static readonly string ContentIndex_min_css = Url("ContentIndex.min.css");
                    public static readonly string CreateProduct_scss = Url("CreateProduct.scss");
                    public static readonly string CreateProduct_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/CreateProduct.min.css") ? Url("CreateProduct.min.css") : Url("CreateProduct.css");
                         
                    public static readonly string CreateProduct_css_map = Url("CreateProduct.css.map");
                    public static readonly string CreateProduct_min_css = Url("CreateProduct.min.css");
                    public static readonly string EditorView_scss = Url("EditorView.scss");
                    public static readonly string EditorView_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/EditorView.min.css") ? Url("EditorView.min.css") : Url("EditorView.css");
                         
                    public static readonly string EditorView_css_map = Url("EditorView.css.map");
                    public static readonly string EditorView_min_css = Url("EditorView.min.css");
                    public static readonly string main_scss = Url("main.scss");
                    public static readonly string main_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/main.min.css") ? Url("main.min.css") : Url("main.css");
                         
                    public static readonly string main_css_map = Url("main.css.map");
                    public static readonly string main_min_css = Url("main.min.css");
                    public static readonly string reset_scss = Url("reset.scss");
                    public static readonly string reset_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/reset.min.css") ? Url("reset.min.css") : Url("reset.css");
                         
                    public static readonly string reset_css_map = Url("reset.css.map");
                    public static readonly string reset_min_css = Url("reset.min.css");
                    public static readonly string Statistics_scss = Url("Statistics.scss");
                    public static readonly string Statistics_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Statistics.min.css") ? Url("Statistics.min.css") : Url("Statistics.css");
                         
                    public static readonly string Statistics_css_map = Url("Statistics.css.map");
                    public static readonly string Statistics_min_css = Url("Statistics.min.css");
                    public static readonly string UserDetails_scss = Url("UserDetails.scss");
                    public static readonly string UserDetails_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/UserDetails.min.css") ? Url("UserDetails.min.css") : Url("UserDetails.css");
                         
                    public static readonly string UserDetails_css_map = Url("UserDetails.css.map");
                    public static readonly string UserDetails_min_css = Url("UserDetails.min.css");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Images {
                    private const string URLPATH = "~/Areas/Admin/Content/Images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string selectboxbtn_nonactive_png = Url("selectboxbtn-nonactive.png");
                    public static readonly string selectboxbtn_png = Url("selectboxbtn.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class web {
                    private const string URLPATH = "~/Areas/Admin/Content/web";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string AdminProductsList_html = Url("AdminProductsList.html");
                }
            
            }
        
        }
    }
    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string AccSzczegZam_js = "~/Scripts/AccSzczegZam.js"; 
                public const string angular_js = "~/Scripts/angular.js"; 
                public const string angular_min_js = "~/Scripts/angular.min.js"; 
                public const string CartSummary_js = "~/Scripts/CartSummary.js"; 
                public const string Chart_js = "~/Scripts/Chart.js"; 
                public const string Chart_min_js = "~/Scripts/Chart.min.js"; 
                public const string jquery_2_1_1_min_js = "~/Scripts/jquery-2.1.1.min.js"; 
                public const string jquery_2_1_3_intellisense_js = "~/Scripts/jquery-2.1.3.intellisense.js"; 
                public const string jquery_2_1_3_js = "~/Scripts/jquery-2.1.3.js"; 
                public const string jquery_2_1_3_min_js = "~/Scripts/jquery-2.1.3.min.js"; 
                public const string jquery_ui_1_11_3_js = "~/Scripts/jquery-ui-1.11.3.js"; 
                public const string jquery_ui_1_11_3_min_js = "~/Scripts/jquery-ui-1.11.3.min.js"; 
                public const string jquery_ui_js = "~/Scripts/jquery-ui.js"; 
                public const string jquery_ui_min_js = "~/Scripts/jquery-ui.min.js"; 
                public const string jquery_elevatezoom_js = "~/Scripts/jquery.elevatezoom.js"; 
                public const string jquery_unobtrusive_ajax_js = "~/Scripts/jquery.unobtrusive-ajax.js"; 
                public const string jquery_unobtrusive_ajax_min_js = "~/Scripts/jquery.unobtrusive-ajax.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string Konto_js = "~/Scripts/Konto.js"; 
                public const string KontoNieaktywne_js = "~/Scripts/KontoNieaktywne.js"; 
                public const string Login_js = "~/Scripts/Login.js"; 
                public const string modernizr_2_8_3_js = "~/Scripts/modernizr-2.8.3.js"; 
                public const string OrderKrok1_js = "~/Scripts/OrderKrok1.js"; 
                public const string OrderKrok2_js = "~/Scripts/OrderKrok2.js"; 
                public const string podsumowanie_js = "~/Scripts/podsumowanie.js"; 
                public const string Register_js = "~/Scripts/Register.js"; 
                public const string Resetuj_js = "~/Scripts/Resetuj.js"; 
                public const string shopAngular_js = "~/Scripts/shopAngular.js"; 
                public const string shopdetails_js = "~/Scripts/shopdetails.js"; 
                public const string ZapomnianeHaslo_js = "~/Scripts/ZapomnianeHaslo.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class css 
            {
                public static partial class Error 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Home 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Konto 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Koszyk 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Sklep 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Zamowienie 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                    public const string jquery_ui_css = "~/Content/css/jquery-ui.css";
                    public const string jquery_ui_structure_css = "~/Content/css/jquery-ui.structure.css";
                }
            }
            public static partial class fonts 
            {
                public static class Assets
                {
                }
            }
            public static partial class Images 
            {
                public static partial class Panels 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Shop 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class themes 
            {
                public static partial class @base 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                        public const string accordion_css = "~/Content/themes/base/accordion.css";
                        public const string all_css = "~/Content/themes/base/all.css";
                        public const string autocomplete_css = "~/Content/themes/base/autocomplete.css";
                        public const string base_css = "~/Content/themes/base/base.css";
                        public const string button_css = "~/Content/themes/base/button.css";
                        public const string core_css = "~/Content/themes/base/core.css";
                        public const string datepicker_css = "~/Content/themes/base/datepicker.css";
                        public const string dialog_css = "~/Content/themes/base/dialog.css";
                        public const string draggable_css = "~/Content/themes/base/draggable.css";
                        public const string menu_css = "~/Content/themes/base/menu.css";
                        public const string progressbar_css = "~/Content/themes/base/progressbar.css";
                        public const string resizable_css = "~/Content/themes/base/resizable.css";
                        public const string selectable_css = "~/Content/themes/base/selectable.css";
                        public const string selectmenu_css = "~/Content/themes/base/selectmenu.css";
                        public const string slider_css = "~/Content/themes/base/slider.css";
                        public const string sortable_css = "~/Content/themes/base/sortable.css";
                        public const string spinner_css = "~/Content/themes/base/spinner.css";
                        public const string tabs_css = "~/Content/themes/base/tabs.css";
                        public const string theme_css = "~/Content/themes/base/theme.css";
                        public const string tooltip_css = "~/Content/themes/base/tooltip.css";
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class web 
            {
                public static class Assets
                {
                }
            }
            public static class Assets
            {
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108


